jakejack13/SPEED

- leaders/src/main/java/edu/cornell/repository/Repository.java
- workers/src/main/java/edu/cornell/repository/Repository.java
- workers/src/main/java/edu/cornell/testenv/testcontext/JUnitContextClassLoader.java
- workers/src/main/java/edu/cornell/testenv/testrunner/JUnit5TestRunner.java
Temporary hotfix till further investigation resolves the underlying issue.
> Remove URL filter to fix test discoverer and add extra logging

- .github/workflows/first-cd.yml
- .github/workflows/first-ci.yml
- first/Dockerfile
- first/main.py
This PR creates the boilerplate functionality for first, the first-tier microservice responsible for serving requests for new SPEED deployments. It contains three endpoints, `start`, `info`, and `update`. More information can be found in 
https://github.com/users/jakejack13/projects/3/views/8?pane=issue&itemId=50750550 
Issue: #25
> #25: [First] Create Flask server with leader creation functionality

- leaders/Dockerfile
- leaders/build.gradle
- workers/Dockerfile
- workers/build.gradle
- workers/src/main/java/edu/cornell/testoutputstream/KafkaTestOutputStream.java
> #52: Change Java version to 21

- leaders/gradle/wrapper/gradle-wrapper.properties
- workers/gradle/wrapper/gradle-wrapper.properties
> #55: Change gradle version to 8.5

- microservices/first/Dockerfile
- microservices/first/main.py
- microservices/first/requirements.txt
- microservices/first/utils/db_manager.py
- microservices/first/utils/docker_runner.py
> #48: Add MyPy to first CI

- .github/workflows/optimizer-cd.yml
- .github/workflows/optimizer-ci.yml
- microservices/optimizer/.gitignore
- microservices/optimizer/Dockerfile
- microservices/optimizer/main.py
- microservices/optimizer/optimizer_api_doc.MD
- microservices/optimizer/requirements.txt
- microservices/optimizer/utils/__init__.py
- microservices/optimizer/utils/db_manager.py
- microservices/optimizer/utils/optimizer.py
> #43: [Optimizer] Create boilerplate optimizer service

- microservices/first/Dockerfile
- microservices/optimizer/Dockerfile
> #59: Update Python to 3.12

- .github/workflows/optimizer-cd.yml
> #61: Fix name of optimizer CD workflow

- leaders/src/main/java/edu/cornell/Main.java
> #39: Add NUM_WORKERS documentation in leader

- microservices/first/Dockerfile
- microservices/first/main.py
- microservices/first/requirements.txt
- microservices/first/utils/db_manager.py
- microservices/first/utils/deployment_status.py
- microservices/first/utils/docker_runner.py
- microservices/optimizer/Dockerfile
- microservices/optimizer/main.py
- microservices/optimizer/requirements.txt
- microservices/optimizer/utils/optimizer.py
> #64: Add static analysis tools to Docker CI for Python 

- Makefile
> #68: Create Makefile to run all commands for all repositories

- microservices/first/first_api_doc.MD
- microservices/first/main.py
- microservices/first/utils/db_manager.py
- microservices/optimizer/main.py
> #45: [First] Create better error handling and logging in microservices

- .github/dependabot.yml
> #76: Add dependency updating

- microservices/first/requirements.txt
> #91: Fix psycopg import bug

- leaders/Dockerfile
- workers/Dockerfile
> #93: Fix leader and worker unable to build repo bug

- microservices/first/app.py
- microservices/optimizer/app.py
> #106: Fix code scanning alert - Flask app is run in debug mode

- leaders/src/main/java/edu/cornell/repository/RepositoryFactory.java
- workers/src/main/java/edu/cornell/repository/RepositoryFactory.java
> #120:  Fix code scanning alert - Log Injection

- .github/workflows/compose-ci.yml
- docker-compose.yml
> #153: Add Docker Compose GitHub Action

- README.md
> #164, #165: Add system specification and usage instructions to README

- microservices/optimizer/poetry.lock
This reverts commit 7b01b6dbd577301e263412d0baf50396f809a0a9.
> Revert "Bump pymongo from 4.10.1 to 10.10.10.10 in /microservices/optimizer (#398)"
